"use client";
import { ArrowRight, ArrowUpRight, Check, Menu, X } from "lucide-react";
import { useState } from "react";
const categories=[
  {n:"01",title:"Business Registration",text:"Start your business with registration and incorporation assistance.",service:"Private Limited Company Registration",active:true},
  {n:"02",title:"Tax & Government Registrations",text:"Handle essential registrations and government-related business requirements.",items:"GST Registration · PAN Application · TAN Application · Udyam / MSME Registration"},
  {n:"03",title:"Directors & Company Changes",text:"Assistance with common director and company-related changes.",items:"Director changes · DIN-related services · Registered Office Change"},
  {n:"04",title:"Corporate Compliance",text:"Support for recurring corporate and ROC compliance requirements.",items:"Annual ROC Compliance · AOC-4 · MGT-7 · DIR-3 KYC"},
  {n:"05",title:"Accounting & Business Support",text:"Practical accounting, bookkeeping, tax and business support for growing businesses."},
  {n:"06",title:"Company Closure",text:"Assistance with company closure and related compliance requirements."}
];
export default function Home(){
 const [menu,setMenu]=useState(false);
 return <main>
  <header className="topbar"><a href="#top" className="brand"><span className="brand-mark"><img src="/taxbro-mark.jpeg" alt="TaxBro"/></span><span>TAXBRO <i>SERVICES</i></span></a><nav className={menu?"nav open":"nav"}><a href="#services" onClick={()=>setMenu(false)}>Services</a><a href="#registration" onClick={()=>setMenu(false)}>Business Registration</a><a href="#compliance" onClick={()=>setMenu(false)}>Compliance</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav><a className="nav-cta" href="#contact">Get Started <ArrowUpRight size={16}/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">BUSINESS • TAX • REGISTRATION • COMPLIANCE</p><h1>Business services,<br/><em>without the</em><br/>complexity.</h1><p className="lede">From starting a business to handling registrations, company changes and ongoing compliance, TaxBro Services helps you get essential business work done in one place.</p><div className="actions"><a href="#services" className="button">Explore Services <span>↓</span></a><a href="#contact" className="text-link">Get Started <ArrowRight size={16}/></a></div></div><div className="hero-art"><div className="orb orb-one"/><div className="orb orb-two"/><div className="orbit"><span>START / REGISTER / MANAGE / COMPLY /</span></div><div className="hero-card"><span>TAXBRO SERVICES</span><strong>One place for<br/>business work.</strong><div><Check size={20}/><small>Clear services. Practical assistance.</small></div></div></div><div className="hero-foot"><span>SCROLL TO EXPLORE</span><span>BUSINESS SERVICES · INDIA</span></div></section>
  <section className="services section" id="services"><div className="section-head"><p className="section-label">01 / SERVICES</p><div><h2>Services for every stage of your business.</h2><p>Choose a service, understand what&apos;s included, and get the assistance you need.</p></div></div><div className="cards">{categories.map(c=><article className="service-card" id={c.n==="01"?"registration":c.n==="04"?"compliance":undefined} key={c.n}><span>{c.n}</span><h3>{c.title}</h3><p>{c.text}</p>{c.active?<div className="service-action"><strong>{c.service}</strong><a href="/services/private-limited-company-registration">View Service <ArrowUpRight size={17}/></a></div>:<div className="future"><small>{c.items||"Services will be introduced here."}</small><em>Coming soon</em></div>}</article>)}</div></section>
  <section className="journey section"><p className="section-label">02 / YOUR BUSINESS JOURNEY</p><div><h2>One platform for your <em>business journey.</em></h2><p>Your business needs different services at different stages. TaxBro Services brings them together in one place.</p><div className="journey-steps">{["Start","Register","Set up","Manage","Stay compliant","Make changes","Close"].map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="how section"><div><p className="section-label">03 / HOW IT WORKS</p><h2>Get business work <em>moving.</em></h2></div><div className="steps">{[["01","Choose a service"],["02","Share your requirements"],["03","Get assistance from TaxBro Services"]].map(([n,t])=><article key={n}><span>{n}</span><h3>{t}</h3></article>)}</div></section>
  <section className="contact section" id="contact"><div><p className="section-label">04 / START HERE</p><h2>Need help with a<br/><em>business service?</em></h2><p className="contact-copy">Tell us what you need and we&apos;ll help you find the right service.</p></div><div className="contact-actions"><a href="/services/private-limited-company-registration" className="button">Get Started <ArrowUpRight size={18}/></a><a href="#services" className="outline-button">Explore Services <ArrowRight size={17}/></a></div></section>
  <footer><div><a className="brand" href="#top"><span className="brand-mark"><img src="/taxbro-mark.jpeg" alt="TaxBro"/></span><span>TAXBRO <i>SERVICES</i></span></a><p>Business, tax, registration and compliance services for businesses in India.</p></div><div className="footer-links"><a href="#services">Services</a><a href="#contact">Contact</a><a href="#top">Back to top ↑</a></div></footer>
 </main>
}
