"use client";
import { useEffect, useRef, useState } from "react";

const cursorFiles:Record<string,string>={default:"default.png",hover:"hover.png",click:"click.png",text:"text.png",help:"help.png",status:"status.png"};
const moments=[
  ["2022","Started where the details matter","My way into tax and compliance started with the unglamorous bits: reading, checking, getting it right."],
  ["2024","More moving parts","E-invoicing, indirect tax, corporate accounting — a wider view of how work actually gets done."],
  ["Now","TaxBro","A useful place for HSN/SAC lookups, MCA codes, MSME checks, invoices, TT rates and the questions around them."],
  ["In progress","ACCA + a lot of tabs open","Still learning, still building, still turning notes into things I can click."],
];
function useMagnet<T extends HTMLElement>(){const ref=useRef<T>(null);useEffect(()=>{const el=ref.current;if(!el||matchMedia("(pointer:coarse)").matches)return;const move=(e:MouseEvent)=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.14}px, ${(e.clientY-r.top-r.height/2)*.14}px)`};const leave=()=>el.style.transform="";el.addEventListener("mousemove",move);el.addEventListener("mouseleave",leave);return()=>{el.removeEventListener("mousemove",move);el.removeEventListener("mouseleave",leave)}},[]);return ref}
export default function DigitalWorld(){
 const [cursor,setCursor]=useState("default"),[visible,setVisible]=useState(false),[open,setOpen]=useState<number|null>(null),[secret,setSecret]=useState(0); const cursorRef=useRef<HTMLDivElement>(null);const glowRef=useRef<HTMLDivElement>(null);const buttonRef=useMagnet<HTMLButtonElement>();
 useEffect(()=>{if(matchMedia("(pointer:coarse)").matches||matchMedia("(prefers-reduced-motion: reduce)").matches)return;let tx=0,ty=0,x=-100,y=-100,raf=0;const tick=()=>{x+=(tx-x)*.18;y+=(ty-y)*.18;if(cursorRef.current)cursorRef.current.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`;if(glowRef.current)glowRef.current.style.transform=`translate(${tx}px,${ty}px) translate(-50%,-50%)`;raf=requestAnimationFrame(tick)};const move=(e:MouseEvent)=>{tx=e.clientX;ty=e.clientY;setVisible(true);const t=e.target as HTMLElement;setCursor(t.closest("button,a,[data-face='help']")?"hover":t.closest("p,h1,h2,h3")?"text":"default")};const down=()=>setCursor("click");const up=()=>setCursor("default");window.addEventListener("mousemove",move);window.addEventListener("mousedown",down);window.addEventListener("mouseup",up);raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);window.removeEventListener("mousemove",move);window.removeEventListener("mousedown",down);window.removeEventListener("mouseup",up)}},[]);
 return <main className="site"><div className="grain"/><div className="ambient" ref={glowRef}/><div ref={cursorRef} className={`face-cursor ${visible?"":"hidden"}`}><img src={`/cursors/${cursorFiles[cursor]}`} alt=""/></div>
 <nav className="nav"><a href="#top">SAHIL / 01</a><div className="nav-links"><a href="#build">TaxBro</a><a href="#world">Elsewhere</a><a href="#contact">Say hi</a></div></nav>
 <section id="top" className="hero"><div className="hero-intro"><div className="eyebrow">Sahil’s internet corner / EST. whenever curiosity hit</div><h1><span><i>Work.</i></span><span><i>Make.</i></span><span><i>Wander.</i></span></h1><p className="hero-copy">Tax and compliance on one screen. Sites, tools, AI experiments and visual rabbit holes on the other. This is where all those tabs meet.</p><button ref={buttonRef} className="magnetic" onClick={()=>document.querySelector("#identity")?.scrollIntoView()}>start exploring <b>↓</b></button></div><div className="hero-machine" data-face="help"><div className="machine-top"><span>SAHIL.OS</span><span>LIVE / 26</span></div><div className="machine-main"><div className="portrait-window"><img src="/cursors/status.png" alt="Sahil"/><span>online, allegedly</span></div><div className="machine-copy"><p>THE PERSONAL<br/>SYSTEM</p><small>built from curiosity,<br/>compliance &amp; Ctrl+T</small></div></div><div className="machine-stream"><span>BUILDING THINGS</span><span>LOOKING THINGS UP</span><span>MAKING A MESS</span><span>BUILDING THINGS</span></div><div className="machine-bottom"><span>01 / TAXBRO</span><span>02 / IDEAS</span><span>03 / NOW</span></div></div><div className="scroll-mark">SCROLL TO ENTER</div></section>
 <section id="identity" className="section identity"><div><div className="index">01 / not a list of job titles</div><h2>One brain.<br/>Several open loops.</h2><p className="identity-copy">The professional side keeps me precise. Building gives that precision somewhere to go. The rest is curiosity, good type, and occasional nonsense.</p><div className="identity-stamp">NOT HERE TO<br/>LOOK CORPORATE</div></div><div className="identity-menu">{[["01","Finance","the details behind the numbers"],["02","Builder","turning repeat problems into tools"],["03","AI / tech","testing what feels useful"],["04","Taste","design, odd references, little experiments"]].map(([n,title,sub],i)=><button className={`identity-row row-${i}`} key={n} data-face="help"><span>{n}</span><strong>{title}</strong><span>{sub} ↗</span></button>)}</div></section>
 <section id="build" className="section tax"><div className="tax-grid"><div><div className="index">02 / one thing I made</div><h2>TaxBro<br/>in motion.</h2><div className="tax-copy"><p>Tax questions often start simple and end with seventeen tabs. TaxBro is my attempt to give the useful answer a proper home.</p><ul className="feature-list"><li>HSN / SAC lookup</li><li>MCA company codes</li><li>MSME classification</li><li>GST invoices + compliance notes</li><li>SBI TT rates</li></ul></div></div><div className="browser" data-face="help"><div className="chrome"><i/><i/><i/><div className="address">taxbro.in / lookup</div></div><div className="product"><aside className="side"><b>TaxBro</b>Lookup<br/>MCA<br/>MSME<br/>Invoices<br/>Rates</aside><div className="dash"><h3>HSN Code Lookup</h3><div className="search">⌕ &nbsp; smartphone</div><div className="result"><div><span className="pill">MATCH FOUND</span><div className="code">85171200</div><small>Telephones for cellular networks.</small></div><div className="bars"><small>QUERY SNAPSHOT</small><i/><i/><i/></div></div></div></div></div></div></section>
 <section className="section"><div className="section-head"><div><div className="index">03 / work, but make it human</div><h2>A few points<br/>on the line.</h2></div><span className="index">tap a point</span></div><div className="timeline">{moments.map(([date,title,text],i)=><article className={`moment ${open===i?"open":""}`} key={date}><button onClick={()=>setOpen(open===i?null:i)} data-face="help"><time>{date}</time><h3>{title} <span>↘</span></h3><p>{text}</p></button></article>)}</div></section>
 <section id="world" className="section playground"><div className="world">ELSEWHERE</div><div className="thought one">AI workflows</div><div className="thought two">still learning</div><div className="thought three">design rabbit holes</div><div className="thought four">future weirdness</div><p className="world-copy">This bit stays intentionally unfinished. A shelf for ideas, visual experiments, interesting links and things I haven’t built yet.</p></section>
 <section id="contact" className="section contact"><div><div className="index">04 / say hello</div><h2>Have an idea?<br/>Let’s make it less boring.</h2><p>For a project, a useful link, or simply a conversation that starts with “what if…”.</p><a className="magnetic" href="mailto:info.taxbro@gmail.com" onClick={(e)=>{if(secret<4){e.preventDefault();setSecret(secret+1)}}}>{secret>=4?"okay, you found the fake email :)":"send a note ↗"}</a></div></section><footer className="footer"><span>© {new Date().getFullYear()} SAHIL</span><span>MADE WITH TOO MANY TABS OPEN</span></footer></main>
}
